version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: bix_app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: bix_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bix_test
      - POSTGRES_PASSWORD=bix_test
      - POSTGRES_DB=bix_test_dev
    ports:
      - 5432:5432  
  
  redis:
    image: redis:5.0.8-alpine
    container_name: bix_redis


volumes:
  postgres_data:
