# Generated by Django 4.2.3 on 2024-11-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_staff_options_alter_staff_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
    ]
