# Generated by Django 4.2.3 on 2024-11-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_staff_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_do_checkin', 'Can do checkin'), ('can_do_checkout', 'Can do checkout')]},
        ),
    ]
