# Generated by Django 4.2.3 on 2024-11-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_staff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
