# Generated by Django 4.2.3 on 2024-11-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_alter_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
