# Generated by Django 4.2.3 on 2024-11-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('staffs', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staff')),
            ],
        ),
    ]
