# Generated by Django 4.2.3 on 2024-11-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_paid_amount_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
