# Generated by Django 4.2.3 on 2024-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance'), ('Cleaning', 'Cleaning'), ('Out of Service', 'Out of Service')], default='Available'),
            preserve_default=False,
        ),
    ]
