# Generated by Django 4.2.3 on 2024-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Luxury Single', 'Luxury Single'), ('Luxury Double', 'Luxury Double')], max_length=255),
        ),
    ]
